/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import org.example.dto.HandlerOutput

class App: RequestHandler<Any?, HandlerOutput> {

    fun hello(): String {
        return "Hello"
    }

    override fun handleRequest(input: Any?, context: Context?): HandlerOutput {
        return HandlerOutput(message = "hello")
    }
}

fun main() {
    println(App().hello())
}
