/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.dto.HandlerInput
import org.example.dto.HandlerOutput
import org.example.github.GitHubApiClient
import org.example.messenger.Messenger
import org.example.support.logger.Logger
import org.junit.jupiter.api.BeforeEach
import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    private lateinit var app: App

    @BeforeEach
    fun setUp() {
        val dummyMessenger =
            object : Messenger {
                override fun sendMessage(
                    text: String,
                    logger: Logger,
                ) {
                    logger.log(text)
                }
            }

        app =
            App(
                messenger = dummyMessenger,
                gitHubApiClient =
                    object : GitHubApiClient(
                        page = 1,
                        perPage = 30,
                        username = "dummy",
                        token = "dummy",
                    ) {
                        override fun getTodayCommitCount(logger: Logger): Int {
                            return 1
                        }
                    },
            )
    }

    @Test
    fun `handleRequest 메서드는 성공 메시지와 커밋 수를 리턴한다`() {
        val consoleLoggerContext = ConsoleLoggerLambdaContext()

        val actual =
            app.handleRequest(
                input = HandlerInput("hi"),
                context = consoleLoggerContext,
            )

        assertEquals(HandlerOutput(message = "success.", todayCommitCount = 1, errorMessage = e.message), actual)
    }
}
