name: Deploy

on:
  push:
    tags:
      - '*'

# https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-clientside
env:
  # also can use `--no-cli-pager` option (instead of `AWS_PAGER: ""`)
  AWS_PAGER: "" # Disable the pager (less)

jobs:
  deploy-to-lambda:
    runs-on: ubuntu-latest

    # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions#using-this-action
    permissions:
      id-token: write # Required for AWS CLI
      contents: read

    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle make jar file
        run: ./gradlew shadowJar

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_LAMBDA_ARN }}

      - name: Deploy to AWS Lambda # NOTE: `app-all.jar` is the jar file name
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://./app/build/libs/app-all.jar

      - name: Get Tag Name
        id: get_tag_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: AWS Lambda Publish Version
        run: |
          aws lambda publish-version \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
            --description "${{ steps.get_tag_name.outputs.TAG }} - ${{ steps.get_short_sha.outputs.SHA }}"
